name: auto-release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: add bundled mingw to path
        shell: cmd
        run: echo resources\mingw64\bin>> %GITHUB_PATH%

      - name: verify toolchain
        shell: cmd
        run: |
          g++ --version
          windres --version

      - name: build exe
        shell: cmd
        run: builder.bat

      - name: rename exe with version
        shell: pwsh
        run: |
          $version = "$env:GITHUB_REF_NAME"
          $newName = "Xylera Valex auto cracker $version.exe"
          Rename-Item -Path "xylera.exe" -NewName $newName
          echo "built $newName"

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xylera-exe
          path: "Xylera Valex auto cracker ${{ github.ref_name }}.exe"

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Xylera Valex auto cracker ${{ github.ref_name }}
          prerelease: false
          draft: false
          files: |
            Xylera Valex auto cracker ${{ github.ref_name }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
